#!/bin/sh
# Wrapper around je_embl_1.0_bundle.jar

#where are we stored ?
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
#echo $DIR
#path to jar file to execute, this jar is supposed to be in the same dir as this script
JAR_FILE=$DIR"/je_embl_1.0_bundle.jar"

OPTS="-Xmx2g"
java $OPTS -jar $JAR_FILE "$@"
exit $?